# Generated by Django 4.2.15 on 2024-08-30 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_weeks', models.PositiveIntegerField()),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('distance_km', models.FloatField()),
                ('elevation_gain_m', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('workout_type', models.CharField(choices=[('easy_run', 'Easy Run'), ('long_run', 'Long Run'), ('tempo_run', 'Tempo Run'), ('intervals', 'Intervals'), ('hill_repeats', 'Hill Repeats'), ('rest', 'Rest'), ('cross_training', 'Cross Training')], max_length=50)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('elevation_gain_m', models.PositiveIntegerField(blank=True, null=True)),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='training_plans.trainingplan')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_plans.trainingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
